# Generated by Django 4.2.28 on 2026-03-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_is_published_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessplan',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', "Sédentaire (Peu ou pas d'exercice)"), ('moderate', 'Modéré (1-3 fois par semaine)'), ('active', 'Actif (3-5 fois par semaine)'), ('elite', 'Élite (6-7 fois par semaine)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wellnessplan',
            name='gender',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wellnessplan',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Perte de Poids'), ('muscle_gain', 'Prise de Masse'), ('maintenance', 'Maintien')], max_length=50),
        ),
    ]
