# Generated by Django 4.2.28 on 2026-03-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wellnessplan_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
