# Generated by Django 4.2.28 on 2026-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exercise_dailylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('breakfast', 'Petit Déjeuner'), ('lunch', 'Déjeuner'), ('dinner', 'Dîner'), ('snack', 'Collation'), ('shake', 'Shake / Smoothie')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=20)),
                ('prep_time_minutes', models.IntegerField(default=15)),
                ('calories', models.IntegerField(default=0)),
                ('protein_g', models.IntegerField(default=0)),
                ('carbs_g', models.IntegerField(default=0)),
                ('fats_g', models.IntegerField(default=0)),
                ('ingredients', models.TextField(help_text='Liste des ingrédients séparés par des sauts de ligne')),
                ('instructions', models.TextField(help_text='Étapes de préparation')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
