# Generated by Django 4.2.28 on 2026-03-18 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customevent',
            name='event_type',
            field=models.CharField(choices=[('sport', 'Sport & fitness'), ('work', 'Travail & carrière'), ('lifestyle', 'Vie perso & loisirs'), ('nutrition', 'Nutrition')], default='work', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Petit déjeuner'), ('lunch', 'Déjeuner'), ('dinner', 'Dîner'), ('snack', 'Collation'), ('shake', 'Shake / Smoothie')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnessplan',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', "Sédentaire (peu ou pas d'exercice)"), ('moderate', 'Modéré (1-3 fois par semaine)'), ('active', 'Actif (3-5 fois par semaine)'), ('elite', 'Élite (6-7 fois par semaine)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wellnessplan',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Perte de poids'), ('muscle_gain', 'Prise de masse'), ('maintenance', 'Maintien')], max_length=50),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_volume', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField(help_text='Poids en kg')),
                ('rest_seconds', models.IntegerField(default=60, help_text='Temps de repos après la série')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_sets', to='api.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.workoutsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
