# Generated by Django 4.2.28 on 2026-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tag_article_tags_comment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="Masqué par l'admin (équivalent soft-delete)"),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP de la dernière connexion', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_user_agent',
            field=models.CharField(blank=True, default='', help_text='User-Agent de la dernière connexion', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de connexions'),
        ),
    ]
