services:
  - type: web
    name: fitwell-monolith
    env: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: bash build_files.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: fitwell-db
          property: connectionString

databases:
  - name: fitwell-db
    databaseName: fitwell
    user: fitwell_user
    plan: free
    region: frankfurt
