services:
  - type: web
    name: fitwell-monolith
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      chmod +x backend/build_files.sh
      ./backend/build_files.sh
      cd backend
      python manage.py seed_exercises
      python manage.py seed_blog
      python manage.py seed_badges
      python manage.py seed_recipes
    startCommand: |
      cd backend
      gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: fitwell-db
          property: connectionString

databases:
  - name: fitwell-db
    databaseName: fitwell
    user: fitwell_user
    plan: free
    region: frankfurt
