# Generated by Django 4.2.28 on 2026-02-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
