# Generated by Django 4.2.28 on 2026-02-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_userplan_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_score',
            field=models.IntegerField(default=0, help_text='Overall health score (0-100)'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
