# Generated by Django 4.2.28 on 2026-02-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_user_health_score_user_level_user_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
    ]
